#!/usr/bin/env python3
from data import text255

def stored_colortable(constantcolor, constantvalue): #ex. blue stays the same at a value of 4, colortable('b', 4)
    if constantcolor == 'r':
        return [[text255(constantvalue, g, b) + 'O' + '\x1b[0;0m' for g in range(0, 260, 5)] for b in range(0, 260, 5)]
    if constantcolor == 'g':
        return [[text255(r, constantvalue, b) + 'O' + '\x1b[0;0m' for r in range(0, 260, 5)] for b in range(0, 260, 5)]
    if constantcolor == 'b':
        return [[text255(r, g, constantvalue) + 'O' + '\x1b[0;0m' for r in range(0, 260, 5)] for g in range(0, 260, 5)]

def arrayprint(array):
    for row in array:
        for elem in range(0, len(row)):
            print(str(row[elem]) + ' ', end='')
        print()

def instant_colortable(constantcolor, constantvalue):
    if constantcolor == 'r':
        for b in range(0, 260, 5):
            for g in range(0, 260, 5):
                print(text255(constantvalue, g, b) + 'O' + '\x1b[0;0m' + ' ', end='')
            print()
    elif constantcolor == 'g':
        for b in range(0, 260, 5):
            for r in range(0, 260, 5):
                print(text255(r, constantvalue, b) + 'O' + '\x1b[0;0m' + ' ', end='')
            print()
    elif constantcolor == 'b':
        for g in range(0, 260, 5):
            for r in range(0, 260, 5):
                print(text255(r, g, constantvalue) + 'O' + '\x1b[0;0m' + ' ', end='')
            print()

if __name__ == "__main__":
    for x in range(0, 51):
        instant_colortable('b', x)