#!/usr/bin/env python3
from data import text5

def stored_colortable(constantcolor, constantvalue): #ex. blue stays the same at a value of 4, colortable('b', 4)
    if constantcolor == 'r':
        return [[text5(constantvalue, g, b) + 'O' + '\x1b[0;0m' for g in range(6)] for b in range(6)]
    if constantcolor == 'g':
        return [[text5(r, constantvalue, b) + 'O' + '\x1b[0;0m' for r in range(6)] for b in range(6)]
    if constantcolor == 'b':
        return [[text5(r, g, constantvalue) + 'O' + '\x1b[0;0m' for r in range(6)] for g in range(6)]

def arrayprint(array):
    for row in array:
        for elem in range(0, len(row)):
            print(str(row[elem]) + ' ', end='')
        print()

def instant_colortable(constantcolor, constantvalue):
    if constantcolor == 'r':
        for b in range(0, 6):
            for g in range(0, 6):
                print(text5(constantvalue, g, b) + 'O' + '\x1b[0;0m' + ' ', end='')
            print()
    elif constantcolor == 'g':
        for b in range(0, 6):
            for r in range(0, 6):
                print(text5(r, constantvalue, b) + 'O' + '\x1b[0;0m' + ' ', end='')
            print()
    elif constantcolor == 'b':
        for g in range(0, 6):
            for r in range(0, 6):
                print(text5(r, g, constantvalue) + 'O' + '\x1b[0;0m' + ' ', end='')
            print()

if __name__ == "__main__":
    for x in range(0, 6):
        instant_colortable('b', x)