#!/usr/bin/env python3
from data import *
def add(n, a): #adds a to n keeping below 5
    if a > 0:
        if n + a <= 5:
            return n + a
        else:
            return 5
    elif a < 0:
        if n + a >= 0:
            return n + a
        else:
            return 0
    else:
        return n

def spectrum():
    for light in range(-5, 6):
        for g in range(0, 6):
            print(f'{text5(add(5, light), add(g, light), add(0, light))}{0}', end='')
        for r in range(4, -1, -1):
            print(f'{text5(add(r, light), add(5, light), add(0, light))}{0}', end='')
        for b in range(0, 6):
            print(f'{text5(add(0, light), add(5, light), add(b, light))}{0}', end='')
        for g in range(4, -1, -1):
            print(f'{text5(add(0, light), add(g, light), add(5, light))}{0}', end='')
        if light == 0:
            print('   main', end='')
        print()
spectrum()