#!/usr/bin/env python3
import tkinter
import time
tk = tkinter.Tk() #important
canvas = tkinter.Canvas(tk, width=500, height=500)
canvas.pack()

main = canvas.create_polygon(210, 210, 300, 210, 300, 310)

def move(event):
    if event.keysym == 'Up':
        canvas.move(main, 0, -5)
    if event.keysym == 'Down':
        canvas.move(main, 0, 5)
    if event.keysym == 'Left':
        canvas.move(main, -5, 0)
    if event.keysym == 'Right':
        canvas.move(main, 5, 0)
    canvas.update()
canvas.bind_all('<KeyPress-Up>', move)
canvas.bind_all('<KeyPress-Down>', move)
canvas.bind_all('<KeyPress-Left>', move)
canvas.bind_all('<KeyPress-Right>', move)
tkinter.mainloop() #keeps program alive