#!/usr/bin/env python3
import data
def basepair(strand, strand_type, new_strand_type):
    if strand_type.lower() == 'dna':
        if new_strand_type.lower() == 'dna':
            conversion = data.dna_basepair
        if new_strand_type.lower() == 'rna':
            conversion = data.dna_rna_basepair
    if strand_type.lower() == 'rna':
        if new_strand_type.lower() == 'dna':
            conversion = data.rna_dna_basepair
        if new_strand_type.lower() == 'rna':
            conversion = data.rna_basepair
    new_strand = ''
    for x in strand:
        new_strand += conversion[x]
    return new_strand

def amino_acids(mRNA):
    codons = [mRNA[i:i+3] for i in range(0, len(mRNA), 3)]
    try:
        output = [data.rna_codon_chart[x.upper()] for x in codons]
    except KeyError:
        output = [data.rna_codon_chart[x.upper()] for x in codons[:-1]] + [codons[-1]]
    return output

def protein_search(mRNA): #searches mRNA for proteins (only finds things between start and stop codons)
    codons = amino_acids(mRNA)
    
    start_codons = []
    for x in range(0, len(codons)):
        if codons[x] == 'methionine':
            start_codons.append(x)

    stop_codons = []
    for x in range(0, len(codons)):
        if codons[x] == 'stop':
            stop_codons.append(x)

    print(start_codons)
    print(stop_codons)
    print(codons)
    if start_codons[0] > stop_codons[0]:
        print('aaa')

while True:
    print(protein_search(input('mRNA sequence > ')))