#!/usr/bin/env python3
dna_basepair = {
    'A': 'T',
    'T': 'A',
    'C': 'G',
    'G': 'C',
}
rna_basepair = {
    'A': 'U',
    'U': 'A',
    'C': 'G',
    'G': 'C',
}
dna_rna_basepair = {
    'A': 'U',
    'T': 'A',
    'C': 'G',
    'G': 'C',
}
rna_dna_basepair = {
    'A': 'T',
    'U': 'A',
    'C': 'G',
    'G': 'C',
}
rna_codon_chart = {
    'UUU': 'phenylalanine',
    'UUC': 'phenylalanine',
    'UUA': 'leucine',
    'UUG': 'leucine',
    'UCU': 'serine',
    'UCC': 'serine',
    'UCA': 'serine',
    'UCG': 'serine',
    'UAU': 'tyrosine',
    'UAC': 'tyrosine',
    'UAA': 'stop',
    'UAG': 'stop',
    'UGU': 'cysteine',
    'UGC': 'cysteine',
    'UGA': 'stop',
    'UGG': 'tryptophan',
    'CUU': 'leucine',
    'CUC': 'leucine',
    'CUA': 'leucine',
    'CUG': 'leucine',
    'CCU': 'proline',
    'CCC': 'proline',
    'CCA': 'proline',
    'CCG': 'proline',
    'CAU': 'histidine',
    'CAC': 'histidine',
    'CAA': 'glutamine',
    'CAG': 'glutamine',
    'CGU': 'arginine',
    'CGC': 'arginine',
    'CGA': 'arginine',
    'CGG': 'arginine',
    'AUU': 'isoleucine',
    'AUC': 'isoleucine',
    'AUA': 'isoleucine',
    'AUG': 'methionine',
    'ACU': 'threonine',
    'ACC': 'threonine',
    'ACA': 'threonine',
    'ACG': 'threonine',
    'AAU': 'asparagine',
    'AAC': 'asparagine',
    'AAA': 'lysine',
    'AAG': 'lysine',
    'AGU': 'serine',
    'AGC': 'serine',
    'AGA': 'arginine',
    'AGG': 'arginine',
    'GUU': 'valine',
    'GUC': 'valine',
    'GUA': 'valine',
    'GUG': 'valine',
    'GCU': 'alanine',
    'GCC': 'alanine',
    'GCA': 'alanine',
    'GCG': 'alanine',
    'GAU': 'aspartic acid',
    'GAC': 'aspartic acid',
    'GAA': 'glutamic acid',
    'GAG': 'glutamic acid',
    'GGU': 'glycine',
    'GGC': 'glycine',
    'GGA': 'glycine',
    'GGG': 'glycine',
}