#!/usr/bin/env python3
import urllib.request
url = input("wikipedia url > ")
site = urllib.request.urlopen(url)
html = str(site.read())
#hrefs = html.split("<p>")[1].split('<a href="')
#links = []
#for x in range(1, len(hrefs)):
    #if x%2 == 1:
        #links.append(hrefs[x].split('"')[0])
#wikilinks = []
#for x in links:
    #if x[:5] == '/wiki':
        #wikilinks.append(x)
#print(wikilinks)
langlinks = html.split('<span class="nowrap"><small><a href="')
print(langlinks[1])