#!/usr/bin/env python3
tree = {
    'US': {
        "airstrike": [2, 2],
        "blockade": {
            "USSR": {
                "maintain": {
                    "US": {
                        "blockade": [1, 4],
                        "airstrike": [3, 1]
                    }
                },
                "withdraw": [4, 3]
            }
        }
    }
}

x = tree
for i in list(x.keys()):
    if isinstance(i, dict):


for x in list(trees.keys()):
    if isinstance(x, dict):
print(list(tree.keys()))