#!/usr/bin/env python3
tree = {
    'US': {
        "airstrike": [2, 2],
        "blockade": {
            "USSR": {
                "maintain": {
                    "US": {
                        "blockade": [1, 4],
                        "airstrike": [3, 1]
                    }
                },
                "withdraw": [4, 3]
            }
        }
    }
}
def deepest_outcome(scenario):
    pass
print(list(tree.keys()))