#!/usr/bin/env python3
from data import *
import random
import time

deck = pile #imports the 52-card deck data from the data module
random.shuffle(deck) #shuffles the deck

comp_deck = pile[0:26] #gives the computer half the deck
your_deck = pile[26:52] #gives you half of the deck

while len(comp_deck) > 0 and len(your_deck) > 0: #The game will end when either you or the computer runs out of cards
    print('You currently have ' + str(len(your_deck)) + ' cards.')
    battlefield = []
    victor = False
    input('Draw your top card!')
    your_top_card = your_deck[0]
    battlefield.append(your_deck[0]) #You take out your top card and put it in the battlefield
    your_deck.remove(your_deck[0])
    comp_top_card = comp_deck[0]
    battlefield.append(comp_deck[0]) #The computer takes out their top card and puts it in the battlefield
    comp_deck.remove(comp_deck[0])
    print('\nYou played ' + your_top_card)
    print('The computer played ' + comp_top_card + '\n')
    if card_values[your_top_card.split()[0]] > card_values[comp_top_card.split()[0]]:
        victor = True
        your_deck += battlefield #If you win, you get all the cards in the battlefield
        output = 'You won:\n'
        for x in battlefield:
            output += x + '\n'
        print(output)
        battlefield = []
    elif card_values[your_top_card.split()[0]] < card_values[comp_top_card.split()[0]]:
        victor = True
        comp_deck += battlefield
        output = 'The computer won:\n'
        for x in battlefield:
            output += x + '\n'
        print(output)
        battlefield = []
    else:
        print("You tied!\n")
    while victor == False: #If there is a tie, proceed until the tie is broken
        input('War time! Draw a card!') #Face down card
        battlefield.append(your_deck[0])
        your_deck.remove(your_deck[0])
        input('Draw another!') #Face up card, used to decide the war
        your_top_card = your_deck[0]
        battlefield.append(your_deck[0])
        your_deck.remove(your_deck[0])
        battlefield.append(comp_deck[0]) #Computer picks a face down card
        comp_deck.remove(comp_deck[0])
        comp_top_card = comp_deck[0] #Face-up card of computer
        battlefield.append(comp_deck[0])
        comp_deck.remove(comp_deck[0])
        print('\nYou played ' + your_top_card)
        print('The computer played ' + comp_top_card + '\n')
        if card_values[your_top_card.split()[0]] > card_values[comp_top_card.split()[0]]:
            victor = True
            your_deck += battlefield #If you win, you get all the cards in the battlefield
            output = 'You won:\n'
            for x in battlefield:
                output += x + '\n'
            print(output)
            battlefield = []
        elif card_values[your_top_card.split()[0]] < card_values[comp_top_card.split()[0]]:
            victor = True
            comp_deck += battlefield
            output = 'The computer won:\n'
            for x in battlefield:
                output += x + '\n'
            print(output)
            battlefield = []
        else:
            print("You tied!\n")
            print('The battlefield currently has ' + str(len(battlefield)) + ' cards.')