#!/usr/bin/env python3
def default_grid(width, height):
    return [[0] * width for i in range(height)]

def printgrid(grid): #prints the grid data to the screen
    print('\033[2J') #clears screen
    for row in grid:
        for square in row:
            print(square, end='')
        print('')

def editsquare(grid, x, y, char): #top-left is 1, 1, changes a certain square to the given character
    grid[y-1][x-1] = char[-1] #last character if more than one character

if __name__ == "__main__":
    import time
    plane = default_grid(31, 15)
    printgrid(plane)
    editsquare(plane, 31, 15, 'a')
    time.sleep(1)
    printgrid(plane)