#!/usr/bin/env python3
import tkinter
import time
tk = tkinter.Tk() #important
canvas = tkinter.Canvas(tk, width=500, height=500)
canvas.pack()

import time
canvas.create_text(200, 200, text='cyka blyat', font=('Times', 22)) #create text
tk.update()
time.sleep(1)
canvas.itemconfig(1, text='polska kurwa') #edit text

tkinter.mainloop() #keeps program alive