#!/usr/bin/env python3
import skilstak.colors as c
import sys
inputs = sys.argv #number, starting base, ending base
if len(inputs) == 4:
    num = int(inputs[1])
    startbase = int(inputs[2])
    endbase = int(inputs[3])
    digits = []
    for x in range(0, len(str(num))):
        digits.append(int(((str(num))[x]))*(startbase**(((len(str(num)))-(x+1))))) #adds digit value, apparent number times base to a power
    #print(digits)
    num = 0
    for x in range(0, len(digits)):
        num += int(digits[x]) #convers to base 10, adds digit values together
    if endbase == 10:
        print(num)
    else:
        while len(digits) != 0:
            digits.remove(digits[0])
        for x in range(0, len(str(num))):
            digits.append(int((str(num))[x])*(10**int((len(str(num))-x-1))))
        #print(digits)
        for x in range(0, len(digits)):
            num += digits[x]
        num = num/2
        #print(num)
        x = 0
        power = 0
        while int(endbase)**power <= num:
            power += 1
        power -= 1
        #print(power)
        while len(digits) != 0:
            digits.remove(digits[0])
        for x in range(power, -1, -1):
            digits.append(str(int((num//(endbase**x)))))
            num = num%(endbase**x)
        #print(digits)
        num = ''
        for x in range(0, len(digits)):
                num += digits[x]
        print(num)
else:
    print(c.r + "Requires 3 inputs, (number) (startbase) (endbase)")
