#!/usr/bin/env python3
while True:
    expression = input("enter an expression > ")
    split_expression = []
    for x in expression:
        if x.isdigit() and len(split_expression) > 0 and split_expression[-1].isdigit():
            split_expression[-1] += x
        else:
            if x != ' ':
                split_expression.append(x)
    for x in range(0, len(split_expression)):
        if split_expression[x].isdigit():
            split_expression[x] = int(split_expression[x])
    print(split_expression)