#!/usr/bin/env python3
def bigger_price(limit, data):
    items = []
    prices = []
    for dict in data:
        prices.append(dict["price"])
    print(prices)
    while len(prices) > limit:
        prices.remove(min(prices))
    print(prices)
    orderedprices = []
    for x in range(0, limit):
        orderedprices.append(max(prices))
        prices.remove(max(prices))
    print(orderedprices)
    for x in orderedprices:
        for y in data:
            if y["price"] == x:
                items.append(y)
    return items
print(bigger_price(2, [
        {"name": "bread", "price": 100},
        {"name": "wine", "price": 138},
        {"name": "meat", "price": 15},
        {"name": "water", "price": 1}
    ]))