#!/usr/bin/env python3
import skilstak.colors as c
import sys
from time import sleep
print(c.r + "Welcome to the cipher program!" + c.x)
message = ''
key = {
        "a": "|",
        "b": "|_",
        "c": "||",
        "d": "|__",
        "e": "|_|",
        "f": "||_",
        "g": "|||",
        "h": "|___",
        "i": "|__|",
        "j": "|_|_",
        "k": "|_||",
        "l": "||__",
        "m": "||_|",
        "n": "|||_",
        "o": "||||",
        "p": "|____",
        "q": "|___|",
        "r": "|__|_",
        "s": "|__||",
        "t": "|_|__",
        "u": "|_|_|",
        "v": "|_||_",
        "w": "|_|||",
        "x": "||___",
        "y": "||__|",
        "z": "||_|_",
        " ": "  "
}
decoder = {y:x for x,y in key.items()}
def encode():
    global message
    encmsg = ''
    for char in message.lower():
        enc = key[char]
        encmsg += (enc + "\\")
    return("Your encoded message is " + c.y + encmsg)

def decode():
    global message
    chars = message.split("\\") #HAIL TIM
    chars.remove(chars[len(chars) - 1])
    decodedmsg = ''
    for char in chars:
        decodedmsg += decoder[char] 
    return(c.clear + "Your decoded message is " + c.y + decodedmsg)
while True:
    choice = input(c.r + "Do you wish to encode or decode a message? " + c.base3 + "> ")
    message = input(c.base3 + "Enter your message: > " + c.cyan)
    if choice.lower() == "encode":
        print(encode())
    elif choice.lower() == "decode":
        print(decode())
    else:
        print(c.r + "Please type encode or decode")
