#!/usr/bin/env python3
import random as r
import skilstak.colors as c
class Fighter:
    def __init__(self, part1, part2):
        self.health = part1
        self.strength = part2
f1 = Fighter(r.randint(1, 10), r.randint(1, 10))
f2 = Fighter(r.randint(1, 10), r.randint(1, 10))
print(c.r + "Fighter " + c.g + "1" + c.r + " has " + c.y + str(f1.health) + c.r + " health and " + c.y + str(f1.strength) + c.r + " strength.")
print(c.r + "Fighter " + c.g + "2" + c.r + " has " + c.y + str(f2.health) + c.r + " health and " + c.y + str(f2.strength) + c.r + " strength.")
if (f1.health + f1.strength) > (f2.health + f2.strength):
    print(c.r + "Therefore, fighter " + c.g + "1 " + c.r + "wins.")
if (f1.health + f1.strength) < (f2.health + f2.strength):
    print(c.r + "Therefore, fighter " + c.g + "2 " + c.r + "wins.")
if (f1.health + f1.strength) == (f2.health + f2.strength):
    print(c.r + "Therefore, it is a " + c.y + "tie!")
