#!/usr/bin/env python3
class Pokemon():
    def __init__(self): #starting data, self is used as the first parameter of methods and for data (self.variable)
        self.attack = 10 #can be modified
        self.hp = 100
    
    def take_damage(self, amount):
        self.hp -= amount

    def hit(self, pokemon):
        pokemon.take_damage(self.attack)

bulb = Pokemon()
charizard = Pokemon()
bulb.hit(charizard)
print(f'object charizard has {charizard.hp} hp')

#the same thing but with dictionaries and functions instead of objects and methods
default_pokemon = {
    'attack': 10,
    'hp': 100
}

def suffer_damage(pokemon, amount):
    pokemon['hp'] -= amount
    return pokemon #pokemon = suffer_damage(pokemon, amount)

def assault(giver, receiver):
    receiver = suffer_damage(receiver, giver['attack'])

bulbd = default_pokemon
charizardd = default_pokemon
assault(bulbd, charizardd)
print(f"dictionary charizard has {charizardd['hp']} hp")