#!/usr/bin/env python3
import skilstak.colors as c
import json
import sys
from urllib.request import urlopen
url = "http://api.fixer.io/latest?base=usd"
with urlopen(url) as request:
    raw = request.read().decode("utf-8")
    data = json.loads(raw)
    print(c.b + "One" + c.r + " USD" + c.b + " is equal to:" + c.reset)
    for exchange in data['rates']:
        print(c.y + str(data['rates'][exchange]) + c.g + " " + exchange)
#l = [str(data['rates']['EUR']), str(data['rates']['GBP']), str(data['rates']['JPY']), str(data['rates']['CAD']), str(data['rates']['NZD']), 
#print("One" + c.r + " USD" + c.reset + " is equal to " + c.b + str(data['rates']['EUR']) + c.y + " euros")
