#!/usr/bin/env python3
import skilstak.colors as c
import time
import random
answers = ['yes', 'no', 'maybe', 'maybe not', 'probably', 'probably not', 'I will think on it', 'it will come to you soon']
special_cases = {'do you love me?': 'NO, YOU ARE THE MOST WORTHLESS BEING IN THE UNIVERSE!!!!!!!!',
        "I hope you die": "Right back at you buddy.",
        "exit": "Ok bye"
        }
print(c.y + "Welcome to the Magic Eightball.")
while True:
    x = str(input(c.cyan + "What is your question?" + c.b3 + " > " + c.cyan))
    if x in special_cases:
        if x == 'exit':
            print(c.r + special_cases[x])
            break
        else:
            print(c.r + special_cases[x])
    else:
        print(c.r + random.choice(answers))

