#!/usr/bin/env python3
import skilstak.colors as c
import sys
print(c.clear + c.o + "WELCOME TO MADLIBZ YOU STAIN ON THE REPUTATION OF HUMANITY!!!")

story = """
Once upon a time, in a {} far away, there lived a group of {} {}
who enjoyed making {} {}.
One day they went to a {}-looking store to restock on {},
and were {} {} by {}.
They were never heard from again!
"""

prompts = [
    "noun",
    "adjective",
    "plural noun",
    "adjective",
    "plural noun",
    "adjective",
    "plural noun",
    "adverb",
    "past tense verb",
    "plural nouns"
]

answers = []

for prompt in prompts: #iterates through the list
    a = input(c.x + "Enter a " + prompt + ":" + c.base3 + "  ")
    answers.append(c.r + a + c.base3)
print(c.clear + story.format(*answers))
