#!/usr/bin/env python3
import time
import sys
def variance(values):
    squared_deviations = []
    for x in values:
        squared_deviations.append((x - (sum(values)/len(values)))**2)
    return sum(squared_deviations)/len(squared_deviations)
l = [1, 2]
while True:
    try:
        if sys.argv[1] == "yes":
            print("\nMean of list 1 to " + str(len(l)) +": " + str(sum(l)/len(l)))
            print("SD of list 1 to " + str(len(l)) +": " + str(variance(l)**.5))
            print("Mean/sd of list 1 to " + str(len(l)) +": " + str((sum(l)/len(l))/(variance(l)**.5)))
            time.sleep(float(sys.argv[2]))
            l.append(len(l)+1)
        else:
            print(str((sum(l)/len(l))/(variance(l)**.5)))
            time.sleep(float(sys.argv[2]))
            l.append(len(l)+1)
    except IndexError:
        print("2 shell arguments required, whether the output is detailed (yes/no) and delay per value\nBy the way it approaches the square root of 3")
        break