#!/usr/bin/env python3
'''A memicious program'''
import skilstak.colors as c
from sys import argv as l
from time import sleep
n = 0
if len(l) == 1:
    try:
        while True:
            print(c.random() + "nyan", end = " ")
    except KeyboardInterrupt:
        print("\nI WANTED TO KEEP RUNNING YOU JERK!")
elif len(l) == 2:
    try:
        while True:
            print(c.random() + (str(l[1])),  end = " ")
    except KeyboardInterrupt:
        print("\nI WANTED TO KEEP RUNNING YOU JERK!")
elif len(l) >= 3:
    while n < int(l[2]):
        print(c.random() + (str(l[1])), end = " ")
        n += 1
    print("")
