#!/usr/bin/env python3
import random
import math

def dieroll(sides, amount): #sums the rolls of multiple dice
  combined_result = 0
  for x in range(0, amount):
    combined_result += math.floor((random.random()*sides) + 1)
  print(combined_result)  

dieroll(6, 1)