#!/usr/bin/env python3
from factormath import *
def decimal_to_frac(nonrepeating, repeating):
    #.33333 inputted as 0, 3
    #.13333 inputted as .1, 3
    #1.3333 inputted as 1, 3
    #1.1333 inputted as 1.1, 3
    if nonrepeating == 0:
        denominator = int('9'*len(str(repeating)))
        gcd = gcf(repeating, denominator)
        return f'{repeating//gcd}/{denominator//gcd}'
while True:
    print(decimal_to_frac(int(input('nonrepeating > ')), int(input('repeating > '))))