#!/usr/bin/env python3
import sys
import skilstak.colors as c
import json
from urllib.request import urlopen
cityname = str(sys.argv[1])
temptype = str(sys.argv[2]).lower()
if temptype == "fahrenheit":
    temptype = "imperial"
if temptype == "celsius":
    temptype = "metric"
if temptype == "imperial":
    vtemp = "Fahrenheit"
elif temptype == "metric":
    vtemp = "Celsius"
elif temptype == "kelvin":
    vtemp = "Kelvin"
request = urlopen("http://api.openweathermap.org/data/2.5/weather?q=" + cityname + "&appid=89ac5df152df034d1ca9d081f065a2e2&units=" + temptype)
raw = request.read().decode("utf-8")
data = json.loads(raw)
print("The temperature in " + c.r + data['name'] + c.b01 + " is " + c.b + str(data['main']['temp']) + " degrees " + c.y + vtemp)
#print(data) #test
