#!/usr/bin/env python3
import tkinter
import time
tk = tkinter.Tk() #important
canvas = tkinter.Canvas(tk, width=500, height=500)
canvas.pack()

main = canvas.create_polygon(100, 100, 200, 100, 200, 200)

def changecolor(event):
    if event.keysym == 'R':
        canvas.itemconfig(main, fill='red')
    if event.keysym == 'G':
        canvas.itemconfig(main, fill='green')
    if event.keysym == 'B':
        canvas.itemconfig(main, fill='blue')
    if event.keysym == '0':
        canvas.itemconfig(main, fill='black')
    canvas.update()
canvas.bind_all('<KeyPress-R>', changecolor)
canvas.bind_all('<KeyPress-G>', changecolor)
canvas.bind_all('<KeyPress-B>', changecolor)
canvas.bind_all('<KeyPress-0>', changecolor)

tkinter.mainloop() #keeps program alive