#!/usr/bin/env python3
import random
from tkinter import *
root = Tk()
frame = Frame(root)
frame.pack()

board = {}
def init(width, height, minecount): #31 by 16 board with 99 mines is expert mode
    for x in range(1, ((width*height) + 1)): #creates spaces row by row
        board[x] = [' ', 'O'] #value, apparent value

    for x in range(0, minecount): #randomly creates 99 mines
        pos = random.randint(1, (width*height)) #picks a random spot to place a mine
        while board[pos] == '*': #if a mine already exists, finds a new place
            pos = random.randint(1, (width*height))
        board[pos] = ['*', 'O']

    #generates number data
    for x in range(1, ((width*height) + 1)):
        if board[x][0] != '*':
            surroundings = [] #list containing the surrounding 8 spaces
            if (x - width) > 0: #if not on the top
                surroundings.append(board[x - width][0]) #space directly above
                if x%width != 0: #if not on the far right
                    surroundings.append(board[x - (width - 1)][0]) #space on the top-right
                if (x-1)%width != 0: #if not on the far left
                    surroundings.append(board[x - (width + 1)][0]) #space on the top-left
            if (x - ((height - 1)*width)) <= 0: #if not on the bottom
                surroundings.append(board[x + width][0]) #space directly below
                if x%width != 0: #if not on the far right
                    surroundings.append(board[x + width + 1][0]) #space on the bottom-right
                if (x - 1)%width != 0: #if not on the far left
                    surroundings.append(board[x + (width - 1)][0]) #space on the bottom-left
            if x%width != 0: #if not on the far right, search space directly to the right
                    surroundings.append(board[x + 1][0]) #space directly to the right
            if (x - 1)%width != 0: #if not on the far left, search space directly to the left
                surroundings.append(board[x - 1][0]) #space directly to the left
            mine_counter = 0
            for i in surroundings: #counts the amount of mines in the surrounding 8 spaces
                if i == '*':
                    mine_counter += 1
            if mine_counter != 0:
                board[x][0] = str(mine_counter) #replaces the empty space with the number of mines in the surrounding 8 spaces

init(31, 16, 99)
w = 31
h = 16
m = 99

class Spot(Button):
    def __init__(self, number, value, apparent):
        super().__init__(master=None)
        data = [number, value, apparent]
        self.config(text=apparent, command=self.leftclick)    
    def leftclick(self):
        self.config(text=value)
    
buttons = {}

def initboard(width, height, minecount):
    for x in range(1, len(board)+1):
        buttons[x] = Spot(x, board[x][0], board[x][1])
    for x in range(1, len(board)+1):
        buttons[x].grid(row=(w//x), column = (w%x))


initboard(31, 16, 99)
root.mainloop()