#!/usr/bin/env python3
import tkinter
import time
tk = tkinter.Tk() #important

canvas = tkinter.Canvas(tk, width=500, height=500)
canvas.pack()

canvas.create_arc(10, 10, 200, 100, extent=180, style=tkinter.ARC) #style of ARC makes it unconnected
#coordinates represent topleft and bottomright, extent is in degrees


canvas.create_arc(250, 250, 450, 450, start=0, extent=270, fill="red")
canvas.create_arc(250, 250, 450, 450, start=270, extent=90, fill="blue") #start allows you to start from a custom degree amount

tkinter.mainloop() #keeps program alive