#!/usr/bin/env python3
import tkinter
tk = tkinter.Tk() #important
canvas = tkinter.Canvas(tk, width=500, height=500)
canvas.pack()

canvas.create_line(0, 0, 500, 500) #line from (0, 0) to (500, 500) - 0,0 is topleft

tkinter.mainloop() #keeps program alive