#!/usr/bin/env python3
import tkinter
import time
import math
tk = tkinter.Tk() #important
canvas = tkinter.Canvas(tk, width=500, height=500)
canvas.pack()

#custom amount of points
coords = 10, 10, 100, 10, 100, 110  #creates a usable tuple for arguments
canvas.create_polygon(coords,  fill='', outline='black') #right triangle, fill='' makes it blank

def create_regular_polygon(sides, centerx, centery, radius, degree_offset=0):
    coordlist = []
    for x in range(0, sides):
        coordlist.append((radius*math.sin((2*x*math.pi/sides)+(degree_offset*math.pi/180))+centerx))
        coordlist.append((radius*math.cos((2*x*math.pi/sides)+(degree_offset*math.pi/180))+centery))
    coordlist = tuple(coordlist)
    canvas.create_polygon(*coordlist)

create_regular_polygon(3, 200, 200, radius=50, degree_offset=0)
create_regular_polygon(3, 300, 300, radius=50, degree_offset=180)
tkinter.mainloop() #keeps program alive